### ISSUE TITLE
[1.12] Random Crash

### ISSUE THREAD

**Issue by MokahTGS** [BigXplosion/FlatBedrock#1]
Getting a random crash with the 1.12 version:

https://pastebin.com/nMaXm1YA

**Comment by DuelMonster** [comment]
I too have just experienced this random crash.  I was currently in the Nether generating new chunks.
<details><summary>Expand for ---- Minecraft Crash Report ----</summary>

```
WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.0-1.12-anarchy.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.18.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 4/12/18 10:04 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.bigxplosion.flatbedrock.world.retrogen.RetroActiveWorldGenerator.onWorldTick(RetroActiveWorldGenerator.java:65)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_296_RetroActiveWorldGenerator_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2751708416 bytes (2624 MB) / 4051697664 bytes (3864 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.2.2654 Optifine OptiFine_1.12.2_HD_U_C8 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State               | ID                         | Version                  | Source                                          | Signature                                |
	|:------------------- |:-------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAAAAAAA | minecraft                  | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | mcp                        | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | FML                        | 8.0.99.99                | forge-1.12.2-14.23.2.2654.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAA | forge                      | 14.23.2.2654             | forge-1.12.2-14.23.2.2654.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAAAAAAA | foamfixcore                | 7.7.4                    | minecraft.jar                                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | actuallyadditions          | 1.12.2-r133              | ActuallyAdditions-1.12.2-r133.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | betterbuilderswands        | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAAAAAAAAAAAA | jei                        | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | blockdrops                 | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | chameleon                  | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | chesttransporter           | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | codechickenlib             | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAAAAAAA | chickenchunks              | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAAAAAAA | clienttweaks               | 3.1.6                    | ClientTweaks_1.12.2-3.1.6.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | endercompass               | 1.2.6.1                  | EnderCompass-1.12-1.2.6.1.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | endercore                  | 1.12.2-0.5.18            | EnderCore-1.12.2-0.5.18.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | enderio                    | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | enderiointegrationtic      | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | enderiobase                | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | enderioconduits            | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | enderiointegrationforestry | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | enderiointegrationticlate  | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | enderiomachines            | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | enderiopowertools          | 5.0.20                   | EnderIO-1.12.2-5.0.20.jar                       | None                                     |
	| UCHIJAAAAAAAAAAAAAA | extrautils2                | 1.0                      | extrautils2-1.12-1.7.6.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | flatbedrockx               | 1.4.0                    | FlatBedrock-1.4.0_1.12.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | foamfix                    | 0.8.0-1.12               | foamfix-0.8.0-1.12-anarchy.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAA | ftblib                     | 5.0.2.10                 | FTBLib-5.0.2.10.jar                             | None                                     |
	| UCHIJAAAAAAAAAAAAAA | ftbutilities               | 5.0.2.8                  | FTBUtilities-5.0.2.8.jar                        | None                                     |
	| UCHIJAAAAAAAAAAAAAA | lunatriuscore              | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | ingameinfoxml              | 2.8.2.94                 | InGameInfoXML-1.12.2-2.8.2.94-universal.jar     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | inventorytweaks            | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAAAAAAAAAAAA | journeymap                 | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | jeresources                | 0.8.6.28                 | JustEnoughResources-1.12.2-0.8.6.28.jar         | None                                     |
	| UCHIJAAAAAAAAAAAAAA | kleeslabs                  | 5.4.8                    | KleeSlabs_1.12.2-5.4.8.jar                      | None                                     |
	| UCHIJAAAAAAAAAAAAAA | malisiscore                | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                    | None                                     |
	| UCHIJAAAAAAAAAAAAAA | malisisblocks              | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAA | malisisdoors               | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                   | None                                     |
	| UCHIJAAAAAAAAAAAAAA | moreoverlays               | 1.13                     | moreoverlays-1.13-mc1.12.1.jar                  | None                                     |
	| UCHIJAAAAAAAAAAAAAA | netherportalfix            | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | quickleafdecay             | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar               | None                                     |
	| UCHIJAAAAAAAAAAAAAA | storagedrawers             | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
	| UCHIJAAAAAAAAAAAAAA | refinedstorage             | 1.5.32                   | refinedstorage-1.5.32.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHIJAAAAAAAAAAAAAA | refinedstorageaddons       | 0.2                      | refinedstorageaddons-0.2.jar                    | None                                     |
	| UCHIJAAAAAAAAAAAAAA | theoneprobe                | 1.4.22                   | theoneprobe-1.12-1.4.22.jar                     | None                                     |
	| UCHIJAAAAAAAAAAAAAA | minersadvantage            | 1.3.14.188               | MinersAdvantage-1.12.2-1.3.14.189.jar           | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.0-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.18.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['DuelMonster'/17677, l='Fox River', x=89.51, y=123.00, z=417.15]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 16
	Multitexture: true
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.01
	OpenGlRenderer: GeForce GTX 970M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
</details>
